In [ ]:
import pandas as pd

def performance(x: int):
    if x <= 10:
        return -1
    elif x <= 12:
        return 0
    elif x <= 19:
        return 1

df = pd.read_csv("student-por.csv", delimiter=";")
display(df.describe())

df['performance'] = df['G3'].apply(lambda x: performance(x))

df.head(100)
display(df.describe())

,age,studytime,failures,freetime,goout,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,1.930663,0.221880,3.180277,3.184900,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,0.829510,0.593235,1.051093,1.175766,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,1.000000,0.000000,3.000000,2.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,0.000000,3.000000,3.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,2.000000,0.000000,4.000000,4.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,3.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

,age,studytime,failures,freetime,goout,health,absences,G1,G2,G3,performance
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,1.930663,0.221880,3.180277,3.184900,3.536210,3.659476,11.399076,11.570108,11.906009,0.121726
std,1.218138,0.829510,0.593235,1.051093,1.175766,1.446259,4.640759,2.745265,2.913639,3.230656,0.845635
min,15.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,16.000000,1.000000,0.000000,3.000000,2.000000,2.000000,0.000000,10.000000,10.000000,10.000000,-1.000000
50%,17.000000,2.000000,0.000000,3.000000,3.000000,4.000000,2.000000,11.000000,11.000000,12.000000,0.000000
75%,18.000000,2.000000,0.000000,4.000000,4.000000,5.000000,6.000000,13.000000,13.000000,14.000000,1.000000
max,22.000000,4.000000,3.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000,1.000000

In [14]:
df.to_csv("studentpf.csv", index=False)